name: chatGPDP
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.9
  - openai==0.27.2
  - python-dotenv==1.0.0
  - pip
  - pip:
      - langchain==0.0.136
      - pyqt5==5.15.9

